stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/train.csv
    outs:
      - data/processed

  augment:
    cmd: python src/data_augmentation.py
    deps:
      - src/data_augmentation.py
      - data/raw/images
    outs:
      - data/augmented

  train:
    cmd: python src/train_models.py
    deps:
      - src/train_models.py
      - data/processed
    outs:
      - models/base
    metrics:
      - metrics.json

  train_aug:
    cmd: python src/train_models_augmented.py
    deps:
      - src/train_models_augmented.py
      - data/augmented
      - data/processed
    outs:
      - models/augmented
    metrics:
      - metrics_aug.json